In [3]:
import numpy as np

Input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,  9, 8,  9, 10, 11, 12, 13, 14, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 0])

print(Input)
a = Input

res = np.r_[True, a[:-1]< a[1:]] & np.r_[a[1:] < a[:-1], True]

print (res)

[ 0  1  2  3  4  5  6  7  8  9 10  9  8  9 10 11 12 13 14 15 14 13 12 11 10
  9  8  7  6  5  4  3  2  1  0]
[False False False False False False False False False False  True False
 False False False False False False False  True False False False False
 False False False False False False False False False False False]


In [4]:
import numpy as np

def NonMaxSuppression(Input, window=60):

    res = np.empty(np.size(Input), dtype=bool)
#     print(np.size(Input))
#     print(res.shape)
    for i, value  in enumerate(Input):
        if (i==0 or i ==np.size(Input)-1):
            res[i] = False
            continue
#         print(i,value)
        if value > Input[i-1] and value > Input[i+1]:
#             print (Input[i-1], value, Input[i+1])
            res[i] = True
            for past in range(int(window/2)):
                if (i-past < 0) : continue
                if (res[i-past] == True and Input[i-past] > Input[i]) : 
                    res[i] = False
                    break
                if (res[i-past] == True and Input[i-past] < Input[i]) :
                    res[i-past] = False
                    
    MaxValues = Input[res==True]
    indexes = np.arange(np.size(Input))[res==True]
    return MaxValues, indexes
        
print((Input))
print(NonMaxSuppression(Input,window=2)[0])
print(NonMaxSuppression(Input,window=2)[1])

[ 0  1  2  3  4  5  6  7  8  9 10  9  8  9 10 11 12 13 14 15 14 13 12 11 10
  9  8  7  6  5  4  3  2  1  0]
[10 15]
[10 19]


In [5]:
from itertools import islice

def window(seq, n=2):
    "Returns a sliding window (of width n) over data from the iterable"
    "   s -> (s0,s1,...s[n-1]), (s1,s2,...,sn), ...                   "
    it = iter(seq)
    result = tuple(islice(it, n))
    if len(result) == n:
        yield result
    for elem in it:
        result = result[1:] + (elem,)
        yield result


In [6]:
for wind in window(range(10), n = 2):
    print(wind)
wind = window(range(10), n = 2)
print (wind)


(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)
(8, 9)
<generator object window at 0x7fd42c0afd58>


In [7]:
import numpy as np 
x=np.arange(5400*512, dtype=np.float32).reshape((5400,512))
print(x.shape)
print (x.dtype)
print(x.strides)
print(x)
x = np.append([x[0,:]]*60, x, axis=0)
x = np.append(x, [x[-1,:]]*60, axis=0)
print(x)
print(x.shape)
print()
results = np.lib.stride_tricks.as_strided(x,shape=(5400,120,512,), strides=(x.strides[0],x.strides[0],x.strides[1]))
print(results.shape)
print(results[60,1,:] - x[0,:])

(5400, 512)
float32
(2048, 4)
[[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   5.09000000e+02
    5.10000000e+02   5.11000000e+02]
 [  5.12000000e+02   5.13000000e+02   5.14000000e+02 ...,   1.02100000e+03
    1.02200000e+03   1.02300000e+03]
 [  1.02400000e+03   1.02500000e+03   1.02600000e+03 ...,   1.53300000e+03
    1.53400000e+03   1.53500000e+03]
 ..., 
 [  2.76326400e+06   2.76326500e+06   2.76326600e+06 ...,   2.76377300e+06
    2.76377400e+06   2.76377500e+06]
 [  2.76377600e+06   2.76377700e+06   2.76377800e+06 ...,   2.76428500e+06
    2.76428600e+06   2.76428700e+06]
 [  2.76428800e+06   2.76428900e+06   2.76429000e+06 ...,   2.76479700e+06
    2.76479800e+06   2.76479900e+06]]
[[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   5.09000000e+02
    5.10000000e+02   5.11000000e+02]
 [  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   5.09000000e+02
    5.10000000e+02   5.11000000e+02]
 [  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   5.0900

In [8]:
(2764287 - 2702848+1)/512

120.0

In [9]:
x=np.arange(0,10).reshape((5,2))
print(x)
print(x[0,:])
# for i in range(60)
x = np.append([x[0,:]]*6, x, axis=0)
# print(x)
x = np.append(x, [x[-1,:]]*6, axis=0)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1]
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [8 9]
 [8 9]
 [8 9]
 [8 9]
 [8 9]
 [8 9]]


In [10]:
x=np.arange(0,10000000).reshape((-1,1000))

# print(x)
nb_frames = x.shape[0]
size_feature = x.shape[1]
sliding_window_seconds = 60 # in seconds
feature_per_second = 2 # number of features per Time_Second
sliding_window_frame = sliding_window_seconds * feature_per_second # number of features per Time_Second
x = np.append([x[0,:]]*int(sliding_window_frame/2), x, axis=0)
x = np.append(x, [x[-1,:]]*int(sliding_window_frame/2), axis=0)

In [14]:
%%time
y = np.lib.stride_tricks.as_strided(x, shape=(int(nb_frames/2), sliding_window_frame, size_feature), strides=(x.strides[0]*2,x.strides[0],x.strides[1]))

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 107 µs


In [15]:
%%time
segment = [x[i:i+sliding_window_seconds,:] for i in range(len(x) - sliding_window_seconds)]

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 12.9 ms


In [13]:
%%time
segment3 = np.array((len(x) - sliding_window_seconds,sliding_window_seconds))
print(segment3.shape)
for i in range(len(x) - sliding_window_seconds):
    segment3[i,:] = x[i:i+sliding_window_seconds]

(2,)


IndexError: too many indices for array

In [33]:
print(nb_frames)
print(y.shape)
print(x)
print(y)

10
(5, 10, 2)
[[ 0  1]
 [ 0  1]
 [ 0  1]
 [ 0  1]
 [ 0  1]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [18 19]
 [18 19]
 [18 19]
 [18 19]
 [18 19]]
[[[ 0  1]
  [ 0  1]
  [ 0  1]
  [ 0  1]
  [ 0  1]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[ 0  1]
  [ 0  1]
  [ 0  1]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]]

 [[ 0  1]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]]

 [[ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]
  [18 19]]

 [[ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]
  [18 19]
  [18 19]
  [18 19]]]


In [43]:
%%time
array = np.arange(100000)
w = 200
segment = [array[i:i+w] for i in range(len(array) - w)]

CPU times: user 76 ms, sys: 0 ns, total: 76 ms
Wall time: 75.7 ms


In [40]:
segment

[array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177